# Generated by Django 5.2.3 on 2025-06-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='time',
        ),
    ]
