# Generated by Django 5.2.3 on 2025-07-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classbasedviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
