# Generated by Django 5.2.3 on 2025-06-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InformationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dropdown', models.CharField(max_length=123)),
                ('checkbox', models.CharField(max_length=123)),
                ('radio_option', models.CharField(max_length=125)),
                ('terms', models.BooleanField(default=True)),
            ],
        ),
    ]
